-
  settings: [ "master" ]

  pagemojit1:
    path: "/pagemojit1"
    call: "@PageMojit.index"
    params:
        src: "routes.yaml"

  pagemojit2:
    path: "/pagemojit2"
    call: "pagemojit.index"
    params:
        src: "routes.yaml"

  default:
    path: "/"
    call: "doc.index"
