-
  settings: [ "master" ]

  doc:
    path: "/"
    call: "doc.index"
    params:
      src: "HTMLFrameMojit"

  page:
    path: "/donotgothere"
    call: "@Page.index"
    params:
      src: "routes.yaml"
